#[derive(Debug, Clone, PartialEq)]
pub struct SearchItemData {
    pub id: usize,
    pub command: &'static str,
    pub c_type: CommandType,
    pub alias: Option<&'static str>,
    pub params: Option<&'static str>,
    pub example: Option<&'static str>,
    pub desc: &'static str,
}

#[derive(Debug, Clone, PartialEq)]
pub enum CommandType {
    Input,
    Function,
    Constant,
    Operation,
    Conversion,
}

impl CommandType {
    pub fn to_string(&self) -> &'static str {
        match self {
            CommandType::Input => "Input type",
            CommandType::Function => "Function",
            CommandType::Constant => "Constant",
            CommandType::Operation => "Operation",
            CommandType::Conversion => "Conversion",
        }
    }
}

pub static SEARCH_ITEMS: &[SearchItemData; 43] = &[
    // START: INPUT COMMANDS
    SearchItemData {
        id: 0,
        command: "variable",
        c_type: CommandType::Input,
        alias: None,
        params: None,
        example: None,
        desc: "Block results are stored in the app state, and can be referenced in other blocks.\nBy default names follow `block_x` notation, but you can be renamed by modifying the block label.\nVariables don't need to be wrapped in quotes, and will evaluate to their corresponding value.",
    },
    SearchItemData {
        id: 1,
        command: "uint256",
        c_type: CommandType::Input,
        alias: None,
        params: None,
        example: Some("0b1010   // bin (10)\n0x1234   // hex (460)\n987650   // hex (987650)\n1.25e6   // scientific notation (1250000)"),
        desc: "EVM word that consists of up to 32 bytes or 256 bits representing an unsigned integer.\nAccepts decimal, hex, or binary inputs. Also supports scientific notation for decimals.\nDue to its integer nature, it doesn't support floating point numbers.\nDue to its unsigned nature, it doesn't support negative numbers.",
    },
    SearchItemData {
        id: 2,
        command: "string",
        c_type: CommandType::Input,
        alias: None,
        params: None,
        example: Some("\"Hello, World!\"   // double quotes ('Hello, World!')\n'Foo Bar'         // single quotes ('Foo Bar')"),
        desc: "Strings must be wrapped around quotation marks. Both single and double quotes are accepted.",
    },
    // END: INPUT COMMANDS
    SearchItemData {
        id: 3,
        command: "unchecked",
        c_type: CommandType::Function,
        alias: None,
        params: None,
        example: Some("unchecked(0 - 1)                     // unchecked operation (max_uint)\nunchecked(format_units(2**256, 4))   // composed unchecked operation ('0.0000')"),
        desc: "Enables unchecked math for any calculation performed inside its brackets.",
    },
    // START: OPERATION COMMANDS
    SearchItemData {
        id: 4,
        command: "+",
        c_type: CommandType::Operation,
        alias: None,
        params: None,
        example: Some("0x11 + 3                  // addition (20)\nmax_uint + 3              // overflowing addition (-) \nunchecked(max_uint + 3)   // unchecked overflowing addition (2)"),
        desc: "Computes the non-overflowing addition of two values.",
    },
    SearchItemData {
        id: 5,
        command: "-",
        c_type: CommandType::Operation,
        alias: None,
        params: None,
        example: Some("0x11 - 3           // substraction (14)\n0 - 1              // underflowing substraction (-) \nunchecked(0 - 1)   // unchecked overflowing substraction (max_uint)"),
        desc: "Computes the non-underflowing subtraction of two values.",
    },
    SearchItemData {
        id: 6,
        command: "*",
        c_type: CommandType::Operation,
        alias: None,
        params: None,
        example: Some("2 * 3                     // multiplication (6)\nmax_uint * 2              // overflowing multiplication (-)\nunchecked(max_uint * 2)   // unchecked overflowing multiplication (max_uint - 1)"),
        desc: "Computes the non-overflowing multiplication of two values.",
    },
    SearchItemData {
        id: 7,
        command: "/",
        c_type: CommandType::Operation,
        alias: None,
        params: None,
        example: Some("9 / 3    // division (3)\n10 / 3   // division rounded down due to integer math (3)"),
        desc: "Computes the division of two values. The result is rounded down to the nearest integer.",
    },
    SearchItemData {
        id: 8,
        command: "%",
        c_type: CommandType::Operation,
        alias: None,
        params: None,
        example: Some("9 % 3    // modulus (0)\n10 % 3   // modulus (1)"),
        desc: "Computes the modulus of two values.",
    },
    SearchItemData {
        id: 9,
        command: "**",
        c_type: CommandType::Operation,
        alias: None,
        params: None,
        example: Some("2 ** 8                // power (256)\n2 ** 256              // overflowing power (-)\nunchecked(2 ** 256)   // unchecked overflowing power (0)"),
        desc: "Computes the power of two values.",
    },
    SearchItemData {
        id: 10,
        command: ">>",
        c_type: CommandType::Operation,
        alias: None,
        params: None,
        example: Some("5 >> 1   // right shift (2)"),
        desc: "Right shift a number by n bits",
    },
    SearchItemData {
        id: 11,
        command: "<<",
        c_type: CommandType::Operation,
        alias: None,
        params: None,
        example: Some("5 << 1   // left shift (10)"),
        desc: "Left shift a number by n bits",
    },
    // END: OPERATION COMMANDS
    // START: FUNCTION COMMANDS
    SearchItemData {
        id: 12,
        command: "sqrt",
        c_type: CommandType::Function,
        alias: None,
        params: None,
        example: Some("sqrt(25)     // square root (5)\nsqrt(30)   // square root rounded down due to integer math (5)"),
        desc: "Computes the square root of the input value. The result is rounded down to the nearest integer.",
    },
    SearchItemData {
        id: 13,
        command: "root",
        c_type: CommandType::Function,
        alias: None,
        params: None,
        example: Some("root(125, 3)   // N root (5)\nroot(130, 3)   // N root rounded down due to integer math (5)"),
        desc: "Computes the Nth root of the input value. The result is rounded down to the nearest integer.",
    },
    SearchItemData {
        id: 14,
        command: "checksum",
        c_type: CommandType::Function,
        alias: Some("addr, address"),
        params: None,
        example: Some("checksum(0xd8da6bf2..7aa96045)   // address checksum (0xd8dA6BF2..7aA96045)"),
        desc: "Calculates the checksum of an Ethereum address",
    },
    SearchItemData {
        id: 15,
        command: "selector",
        c_type: CommandType::Function,
        alias: None,
        params: None,
        example: Some("selector(\"transfer(address,uint256)\")   // 4-byte function selector (0xa9059cbb)"),
        desc: "Returns the 4-byte function selector for Ethereum function signatures.\n The function signature must only the function name followed by the parameter types in parentheses (without parameter names).",
    },
    SearchItemData {
        id: 16,
        command: "keccak256",
        c_type: CommandType::Function,
        alias: Some("sha3"),
        params: None,
        example: Some("keccak256(\"hello world\")   // keccak hash (0x47173285a8d7..fa254cb01fad)"),
        desc: "Computes the KECCAK-256 hash of the input following the SHA-3 standard.",
    },
    SearchItemData {
        id: 17,
        command: "base64_encode",
        c_type: CommandType::Function,
        alias: Some("b64_encode, b64encode"),
        params: None,
        example: Some("b64_encode(\"hello world\")   // base64 encode ('aGVsbG8gd29ybGQ=')"),
        desc: "Encodes the input string into Base64 format",
    },
    SearchItemData {
        id: 18,
        command: "base64_decode",
        c_type: CommandType::Function,
        alias: Some("b64_decode, b64decode"),
        params: None,
        example: Some("b64_decode(\"aGVsbG8gd29ybGQ=\")   // base64 decode ('hello world')"),
        desc: "Decodes the Base64 encoded string back into plain text",
    },
    SearchItemData {
        id: 19,
        command: "abi_encode",
        c_type: CommandType::Function,
        alias: None,
        params: Some("abi_encode(fn_sig: `string`, params: `string`)"),
        example: Some("abi_encode(                                // abi encode without function selector:\n  \"transfer(address,uint256)\",\n  \"0xd8da6bf2..7aa96045, 1\"\n)"),
        desc: "ABI encodes the arguments and outputs the corresponding calldata without the function selector",
    },
    SearchItemData {
        id: 20,
        command: "abi_encode_with_selector",
        c_type: CommandType::Function,
        alias: Some("abi_encode_with_sig"),
        params: None,
        example: Some("abi_encode_with_selector(\"transfer(address,uint256)\", \"0xd8da6bf2..7aa96045, 1\")  // abi encode with the function selector"),
        desc: "ABI encodes the arguments and outputs the corresponding calldata with the function selector",
    },
    SearchItemData {
        id: 21,
        command: "abi_decode",
        c_type: CommandType::Function,
        alias: None,
        params: None,
        example: Some("abi_decode(\"transfer(address,uint256)\", \"0xa9059cbb000000000000..0000001\")  // abi decode"),
        desc: "Decodes calldata given a function signature. Automatically identifies the 8-byte function selectors if present.",
    },
    SearchItemData {
        id: 22,
        command: "debug",
        c_type: CommandType::Function,
        alias: None,
        params: None,
        example: Some("debug(\"0xa9059cbb000000000000..0000001\")  // pretty prints calldata in 32-byte words + function selector"),
        desc: "Pretty prints calldata in 32-byte words. Automatically identifies 8-byte function selectors if present.",
    },
    SearchItemData {
        id: 23,
        command: "uppercase",
        c_type: CommandType::Function,
        alias: Some("upper"),
        params: None,
        example: Some("upper(\"hello\")  // upper case ('HELLO')"),
        desc: "Converts a string to upper case",
    },
    SearchItemData {
        id: 24,
        command: "lowercase",
        c_type: CommandType::Function,
        alias: Some("lower"),
        params: None,
        example: Some("lower(\"WORLD\")  // lower case ('world')"),
        desc: "Converts a string to lower case",
    },
    SearchItemData {
        id: 25,
        command: "len",
        c_type: CommandType::Function,
        alias: Some("chars"),
        params: None,
        example: Some("len(\"foo bar\")  // count all characters (7)"),
        desc: "Returns the length of a string",
    },
    SearchItemData {
        id: 26,
        command: "count",
        c_type: CommandType::Function,
        alias: None,
        params: None,
        example: Some("count(\"foo bar\", \"o\")  // count input character (2)"),
        desc: "Counts occurrences of a substring within a string",
    },
    SearchItemData {
        id: 27,
        command: "left_pad",
        c_type: CommandType::Function,
        alias: Some("lpad"),
        params: None,
        example: None,
        desc: "Pads a string the to the left, with a zeros, to a specified length",
    },
    SearchItemData {
        id: 28,
        command: "right_pad",
        c_type: CommandType::Function,
        alias: Some("rpad"),
        params: None,
        example: None,
        desc: "Pads a string the to the right, with a zeros, to a specified length",
    },
    SearchItemData {
        id: 29,
        command: "format_ether",
        c_type: CommandType::Function,
        alias: None,
        params: None,
        example: Some("format_ether(1e18)  // format with 18 decimal places ('1.000000000000000000')"),
        desc: "Formats the input number with 18 decimal places. Since floating point math is not supported, outputs a string.",
    },
    SearchItemData {
        id: 30,
        command: "format_uints",
        c_type: CommandType::Function,
        alias: None,
        params: None,
        example: Some("format_uints(123456, 4)  // format with n decimal places ('12.3456')"),
        desc: "Formats the input number with a specified number of decimals. Since floating point math is not supported, outputs a string.",
    },
    SearchItemData {
        id: 31,
        command: "unix",
        c_type: CommandType::Function,
        alias: None,
        params: None,
        example: Some("unix(2023, 12, 31, 23, 59, 59)  // unix timestamp, comma separated (1704067199)\nunix(2023-12-31T23:59:59)  // unix timestamp, YYYY-MM-DDTHH:mm:ss (1704067199)\nunix(1704067199)  // formatted timestamp from unix ('2023-12-31 23:59:59')\nunix(1704067199, \"%Y-%m-%dT%H:%M:%S\")  // custom formatted timestamp from unix ('2023-12-31T23:59:59')"),
        desc: "Bidirectional function:\n- Converts a unix timestamp to a human-readable date. Accepts a second argument for the date format.\n- Converts strings of comma-separated values or '%Y-%m-%d %H:%M:%S' format to a unix timestamp.",
    },
    SearchItemData {
        id: 32,
        command: "get_price_from_tick",
        c_type: CommandType::Function,
        alias: Some("get_price, price_from_tick, price_at_tick"),
        params: None,
        example: Some("get_price_from_tick(202919, false, 6, 18)  // get price from tick (\"1 token1 : 1540.921115 token0\")"),
        desc: "Computes the price of a Uniswap V3 pool (in token0 or token1) given a tick value and the token decimals.",
    },
    SearchItemData {
        id: 33,
        command: "get_tick_from_sqrt_ratio",
        c_type: CommandType::Function,
        alias: Some("get_tick, tick_from_sqrt_ratio, tick_from_sqrt_x96"),
        params: None,
        example: Some("get_tick_from_sqrt_ratio(4295128739)  // get tick from sqrt ratio (\"-887272\")"),
        desc: "Computes the tick of a Uniswap V3 pool given a square root of price as a Q64.96.",
    },
    SearchItemData {
        id: 34,
        command: "get_sqrt_ratio_from_tick",
        c_type: CommandType::Function,
        alias: Some("get_sqrt_ratio, get_sqrt_x96, sqrt_ratio_from_tick, sqrt_x96_from_tick"),
        params: None,
        example: Some("get_sqrt_ratio_from_tick(-887272)  // get sqrt ratio from tick (\"4295128739\")"),
        desc: "Computes the square root of price as a Q64.96 give the tick of a Uniswap V3 pool.",
    },
    SearchItemData {
        id: 35,
        command: "get_liquidity_from_amount1",
        c_type: CommandType::Function,
        alias: Some("get_liquidity, liquidity_from_amount1"),
        params: None,
        example: Some("get_liquidity_from_amount1(1e6, 5317859378, 4295128739, 6178424788)  // get liquidity from total amount1 (44928398530981124971653892)"),
        desc: "Computes the equivalent liquidity of a Uniswap V3 range given the pool's sqrtPrice, and the range's amount1, sqrtPa, and sqrtPb.",
    },
    SearchItemData {
        id: 36,
        command: "get_amount0_from_range",
        c_type: CommandType::Function,
        alias: Some("get_amount0, amount0_from_range"),
        params: None,
        example: Some("get_amount0_from_range(44928398530981124971653892, 5317859378, 4295128739, 6178424788)  // get amount0 from liquidity"),
        desc: "Computes the equivalent amount0 of a Uniswap V3 range given the pool's sqrtPrice, and the range's liquidity, sqrtPa, and sqrtPb.",
    },
    SearchItemData {
        id: 37,
        command: "get_amount1_from_range",
        c_type: CommandType::Function,
        alias: Some("get_amount0, amount0_from_range"),
        params: None,
        example: Some("get_amount1_from_range(44928398530981124971653892, 5317859378, 4295128739, 6178424788)  // get amount1 from liquidity"),
        desc: "Computes the equivalent amount1 of a Uniswap V3 range given the pool's sqrtPrice, and the range's liquidity, sqrtPa, and sqrtPb.",
    },
    // END: FUNCTION COMMANDS
    // START: CONVERSION COMMANDS
    SearchItemData {
        id: 38,
        command: "EVM gas units",
        c_type: CommandType::Conversion,
        alias: Some("wei, kwei, mwei, gwei, szabo, finney, ether"),
        params: None,
        example: Some("1 ether to gwei  // gas unit conversion (1000000000)"),
        desc: "Converts the input value to the equivalent amount. Follows the pattern: 'unit_from' to 'unit_to'.\nWhen 'unit_to' is bigger than 'unit_from', the result is rounded down.",
    },
    SearchItemData {
        id: 39,
        command: "Time units",
        c_type: CommandType::Conversion,
        alias: Some("seconds, minutes, hours, days, weeks, months, years"),
        params: None,
        example: Some("1 year to seconds  // time unit conversion (31536000)"),
        desc: "Converts the input value to the equivalent amount. Follows the pattern: 'unit_from' to 'unit_to'.\nWhen 'unit_to' is bigger than 'unit_from', the result is rounded down.",
    },
    // END: CONVERSION COMMANDS
    // START: CONSTANTS
    SearchItemData {
        id: 40,
        command: "max_uint",
        c_type: CommandType::Constant,
        alias: Some("max_u256, type(uint256).max"),
        params: None,
        example: Some("max_uint  // maximum U256 value (0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff)"),
        desc: "Evaluates to the max uint possible with 32 bytes or 256 bits",
    },
    SearchItemData {
        id: 41,
        command: "zero_address",
        c_type: CommandType::Constant,
        alias: Some("address(0), addr(0), address_zero, zadd"),
        params: None,
        example: Some("zero_address  // zero address (0x0000000000000000000000000000000000000000)"),
        desc: "Evaluates to the zero address",
    },
    SearchItemData {
        id: 42,
        command: "now",
        c_type: CommandType::Constant,
        alias: None,
        params: None,
        example: Some("now  // current timestamp"),
        desc: "Evaluates to the current unix timestamp",
    },
];
