#[derive(Debug, Clone, PartialEq)]
pub struct SearchItemData {
    pub id: usize,
    pub command: &'static str,
    pub c_type: CommandType,
    pub alias: Option<&'static str>,
    pub params: Option<&'static str>,
    pub example: Option<&'static str>,
    pub desc: &'static str,
}

#[derive(Debug, Clone, PartialEq)]
pub enum CommandType {
    Input,
    Function,
    Constant,
    Operation,
    Conversion,
}

impl CommandType {
    pub fn to_string(&self) -> &'static str {
        match self {
            CommandType::Input => "Input type",
            CommandType::Function => "Function",
            CommandType::Constant => "Constant",
            CommandType::Operation => "Operation",
            CommandType::Conversion => "Conversion",
        }
    }
}

pub static SEARCH_ITEMS: &[SearchItemData; 43] = &[
    // START: INPUT COMMANDS
    SearchItemData {
        id: 0,
        command: "variable",
        c_type: CommandType::Input,
        alias: None,
        params: None,
        example: None,
        desc: "Block results are stored in the app state, and can be referenced in other blocks.\nBy default names follow `block_x` notation, but you can be renamed by modifying the block label.\nVariables don't need to be wrapped in quotes, and will evaluate to their corresponding value.",
    },
    SearchItemData {
        id: 1,
        command: "uint256",
        c_type: CommandType::Input,
        alias: None,
        params: None,
        example: Some("hex: 0x1234\nbin:0b1010\ndec:98765\nscientific notation:1.25e18"),
        desc: "EVM word that consists of up to 32 bytes or 256 bits representing an unsigned integer.\nAccepts decimal, hex, or binary inputs. Also supports scientific notation for decimals.\nDue to its integer nature, it doesn't support floating point numbers.\nDue to its unsigned nature, it doesn't support negative numbers.",
    },
    SearchItemData {
        id: 2,
        command: "string",
        c_type: CommandType::Input,
        alias: None,
        params: None,
        example: Some("double quotes: \u{0022}Hello, World!\u{0022}\nsingle quotes: 'Foo Bar' // test comment"),
        desc: "Strings must be wrapped around quotation marks. Both single and double quotes are accepted.",
    },
    // END: INPUT COMMANDS
    SearchItemData {
        id: 3,
        command: "unchecked",
        c_type: CommandType::Function,
        alias: None,
        params: None,
        example: None,
        desc: "Enables unchecked math for any calculation performed inside its brackets.",
    },
    // START: OPERATION COMMANDS
    SearchItemData {
        id: 4,
        command: "+",
        c_type: CommandType::Operation,
        alias: None,
        params: None,
        example: None,
        desc: "Computes the non-overflowing addition of two values.",
    },
    SearchItemData {
        id: 5,
        command: "-",
        c_type: CommandType::Operation,
        alias: None,
        params: None,
        example: None,
        desc: "Computes the non-underflowing substraction of two values.",
    },
    SearchItemData {
        id: 6,
        command: "*",
        c_type: CommandType::Operation,
        alias: None,
        params: None,
        example: None,
        desc: "Computes the non-overflowing multiplication of two values.",
    },
    SearchItemData {
        id: 7,
        command: "/",
        c_type: CommandType::Operation,
        alias: None,
        params: None,
        example: None,
        desc: "Computes the division of two values. The result is rounded down to the nearest integer.",
    },
    SearchItemData {
        id: 8,
        command: "%",
        c_type: CommandType::Operation,
        alias: None,
        params: None,
        example: None,
        desc: "Computes the modulus of two values.",
    },
    SearchItemData {
        id: 9,
        command: "**",
        c_type: CommandType::Operation,
        alias: None,
        params: None,
        example: None,
        desc: "Computes the power of two values.",
    },
    SearchItemData {
        id: 10,
        command: ">>",
        c_type: CommandType::Operation,
        alias: None,
        params: None,
        example: None,
        desc: "Right shift a number by n bits",
    },
    SearchItemData {
        id: 11,
        command: "<<",
        c_type: CommandType::Operation,
        alias: None,
        params: None,
        example: None,
        desc: "Left shift a number by n bits",
    },
    // END: OPERATION COMMANDS
    // START: FUNCTION COMMANDS
    SearchItemData {
        id: 12,
        command: "sqrt",
        c_type: CommandType::Function,
        alias: None,
        params: None,
        example: None,
        desc: "Computes the square root of the input value. The result is rounded down to the nearest integer.",
    },
    SearchItemData {
        id: 13,
        command: "root",
        c_type: CommandType::Function,
        alias: None,
        params: None,
        example: None,
        desc: "Computes the nth root of the input value. The result is rounded down to the nearest integer.",
    },
    SearchItemData {
        id: 14,
        command: "checksum",
        c_type: CommandType::Function,
        alias: None,
        params: None,
        example: None,
        desc: "Calculates the checksum of an Ethereum address",
    },
    SearchItemData {
        id: 15,
        command: "selector",
        c_type: CommandType::Function,
        alias: Some("address, addr"),
        params: None,
        example: None,
        desc: "Returns the 4-byte function selector for Ethereum function signatures",
    },
    SearchItemData {
        id: 16,
        command: "keccak256",
        c_type: CommandType::Function,
        alias: Some("sha3"),
        params: None,
        example: None,
        desc: "Computes the KECCAK-256 hash of the input following the SHA-3 standard.",
    },
    SearchItemData {
        id: 17,
        command: "base64_encode",
        c_type: CommandType::Function,
        alias: Some("b64_encode, b64encode"),
        params: None,
        example: None,
        desc: "Encodes the input string into Base64 format",
    },
    SearchItemData {
        id: 18,
        command: "base64_decode",
        c_type: CommandType::Function,
        alias: Some("b64_decode, b64decode"),
        params: None,
        example: None,
        desc: "Decodes the Base64 encoded string back into plain text",
    },
    SearchItemData {
        id: 19,
        command: "abi_encode",
        c_type: CommandType::Function,
        alias: None,
        params: None,
        example: None,
        desc: "ABI encodes the arguments and outputs the corresponding calldata without the function selector",
    },
    SearchItemData {
        id: 20,
        command: "abi_encode_with_selector",
        c_type: CommandType::Function,
        alias: Some("abi_encode_with_sig"),
        params: None,
        example: None,
        desc: "ABI encodes the arguments and outputs the corresponding calldata with the function selector",
    },
    SearchItemData {
        id: 21,
        command: "abi_decode",
        c_type: CommandType::Function,
        alias: None,
        params: None,
        example: None,
        desc: "Decodes calldata given a function signature. Automatically identifies the 8-byte function selectors if present.",
    },
    SearchItemData {
        id: 22,
        command: "debug",
        c_type: CommandType::Function,
        alias: None,
        params: None,
        example: None,
        desc: "Pretty prints calldata in 32-byte words. Automatically identifies 8-byte function selectors if present.",
    },
    SearchItemData {
        id: 23,
        command: "uppercase",
        c_type: CommandType::Function,
        alias: Some("upper"),
        params: None,
        example: None,
        desc: "Converts a string to upper case",
    },
    SearchItemData {
        id: 24,
        command: "lowercase",
        c_type: CommandType::Function,
        alias: Some("lower"),
        params: None,
        example: None,
        desc: "Converts a string to lower case",
    },
    SearchItemData {
        id: 25,
        command: "len",
        c_type: CommandType::Function,
        alias: Some("chars"),
        params: None,
        example: None,
        desc: "Returns the length of a string",
    },
    SearchItemData {
        id: 26,
        command: "count",
        c_type: CommandType::Function,
        alias: None,
        params: None,
        example: None,
        desc: "Counts occurrences of a substring within a string",
    },
    SearchItemData {
        id: 27,
        command: "left_pad",
        c_type: CommandType::Function,
        alias: Some("lpad"),
        params: None,
        example: None,
        desc: "Pads a string the to the left, with a zeros, to a specified length",
    },
    SearchItemData {
        id: 28,
        command: "right_pad",
        c_type: CommandType::Function,
        alias: Some("rpad"),
        params: None,
        example: None,
        desc: "Pads a string the to the right, with a zeros, to a specified length",
    },
    SearchItemData {
        id: 29,
        command: "format_ether",
        c_type: CommandType::Function,
        alias: None,
        params: None,
        example: None,
        desc: "Formats the input number with 18 decimal places. Since floating point math is not supported, outputs a string.",
    },
    SearchItemData {
        id: 30,
        command: "format_uints",
        c_type: CommandType::Function,
        alias: None,
        params: None,
        example: None,
        desc: "Formats the input number with a specified number of decimals. Since floating point math is not supported, outputs a string.",
    },
    SearchItemData {
        id: 31,
        command: "unix",
        c_type: CommandType::Function,
        alias: None,
        params: None,
        example: None,
        desc: "Bidirectional function:\n- Converts a unix timestamp to a human-readable date. Accepts a second argument for the date format.\n- Converts strings of comma-separated values or '%Y-%m-%d %H:%M:%S' format to a unix timestamp.",
    },
    SearchItemData {
        id: 32,
        command: "get_price_from_tick",
        c_type: CommandType::Function,
        alias: Some("get_price, price_from_tick, price_at_tick"),
        params: None,
        example: None,
        desc: "Computes the price of a Uniswap V3 pool (in token0 or token1) given a tick value and the token decimals.",
    },
    SearchItemData {
        id: 33,
        command: "get_tick_from_sqrt_ratio",
        c_type: CommandType::Function,
        alias: Some("get_tick, tick_from_sqrt_ratio, tick_from_sqrt_x96"),
        params: None,
        example: None,
        desc: "Computes the tick of a Uniswap V3 pool given a square root of price as a Q64.96.",
    },
    SearchItemData {
        id: 34,
        command: "get_sqrt_ratio_from_tick",
        c_type: CommandType::Function,
        alias: Some("get_sqrt_ratio, get_sqrt_x96, sqrt_ratio_from_tick, sqrt_x96_from_tick"),
        params: None,
        example: None,
        desc: "Computes the square root of price as a Q64.96 give the tick of a Uniswap V3 pool.",
    },
    SearchItemData {
        id: 35,
        command: "get_liquidity_from_amount1",
        c_type: CommandType::Function,
        alias: Some("get_liquidity, liquidity_from_amount1"),
        params: None,
        example: None,
        desc: "Computes the equivalent liquidity of a Uniswap V3 range given the pool's sqrtPrice, and the range's amount1, sqrtPa, and sqrtPb.",
    },
    SearchItemData {
        id: 36,
        command: "get_amount0_from_range",
        c_type: CommandType::Function,
        alias: Some("get_amount0, amount0_from_range"),
        params: None,
        example: None,
        desc: "Computes the equivalent amount0 of a Uniswap V3 range given the pool's sqrtPrice, and the range's liquidity, sqrtPa, and sqrtPb.",
    },
    SearchItemData {
        id: 37,
        command: "get_amount1_from_range",
        c_type: CommandType::Function,
        alias: Some("get_amount0, amount0_from_range"),
        params: None,
        example: None,
        desc: "Computes the equivalent amount1 of a Uniswap V3 range given the pool's sqrtPrice, and the range's liquidity, sqrtPa, and sqrtPb.",
    },
    // END: FUNCTION COMMANDS
    // START: CONVERSION COMMANDS
    SearchItemData {
        id: 38,
        command: "EVM gas units",
        c_type: CommandType::Conversion,
        alias: Some("wei, kwei, mwei, gwei, szabo, finney, ether"),
        params: None,
        example: None,
        desc: "Converts the input value to the equivalent amount. Follows the pattern: 'unit_from' to 'unit_to'.\nWhen 'unit_to' is bigger than 'unit_from', the result is rounded down.",
    },
    SearchItemData {
        id: 39,
        command: "Time units",
        c_type: CommandType::Conversion,
        alias: Some("seconds, minutes, hours, days, weeks, months, years"),
        params: None,
        example: None,
        desc: "Converts the input value to the equivalent amount. Follows the pattern: 'unit_from' to 'unit_to'.\nWhen 'unit_to' is bigger than 'unit_from', the result is rounded down.",
    },
    // END: CONVERSION COMMANDS
    // START: CONSTANTS
    SearchItemData {
        id: 40,
        command: "max_uint",
        c_type: CommandType::Constant,
        alias: Some("max_u256, type(uint256).max"),
        params: None,
        example: None,
        desc: "Evaluates to the max uint possible with 32 bytes or 256 bits",
    },
    SearchItemData {
        id: 41,
        command: "zero_address",
        c_type: CommandType::Constant,
        alias: Some("address(0), addr(0), address_zero, zadd"),
        params: None,
        example: None,
        desc: "Evaluates to the zero address",
    },
    SearchItemData {
        id: 42,
        command: "now",
        c_type: CommandType::Constant,
        alias: None,
        params: None,
        example: None,
        desc: "Evaluates to the current unix timestamp",
    },
];
